//! Generating a DuckDB view that hides schema evolution from readers.
//!
//! `orc` is write-only, so it cannot help readers at query time. What it can do
//! is emit the SQL they would otherwise have to write themselves — and get
//! subtly wrong the first time. Each flush regenerates
//! `series/<name>/view.sql`, which unions every epoch by name and coalesces
//! promoted keys against `extra`.
//!
//! The file is derived: pure text, rewritable at any moment, reconstructible
//! from the manifest plus the epoch tags in the Parquet filenames. A crash while
//! writing it costs nothing.

use std::collections::BTreeSet;

use crate::config::KeyDef;
use crate::manifest::EpochSchema;
use crate::record::KeyType;

/// SQL string literal quoting: double any embedded single quote.
fn sql_str(s: &str) -> String {
    format!("'{}'", s.replace('\'', "''"))
}

/// The DuckDB type a declared key reads back as, matching what
/// [`crate::flush::parquet::parquet_schema`] writes.
fn duckdb_type(ty: KeyType) -> &'static str {
    match ty {
        KeyType::Bool => "BOOLEAN",
        KeyType::I64 => "BIGINT",
        KeyType::F64 => "DOUBLE",
        KeyType::Str => "VARCHAR",
    }
}

/// Quote an identifier for DuckDB, doubling embedded double quotes.
///
/// Key names come from user config and can contain almost anything, so they are
/// always quoted rather than quoted-if-needed — a column called `select` or
/// `order` is otherwise a syntax error in the generated file.
fn sql_ident(s: &str) -> String {
    format!("\"{}\"", s.replace('"', "\"\""))
}

/// Generate the `CREATE VIEW` text for one series.
///
/// `history` is that series' full epoch history, oldest first. A key present in
/// *every* epoch is selected directly. A key missing from at least one epoch is
/// coalesced against `extra`, because in the epochs where it was not declared
/// its values landed in the overflow map — that is exactly what promoting a key
/// from `extra` looks like on disk, and the coalesce is what makes the two
/// halves read as one column.
pub fn view_sql(series: &str, history: &[EpochSchema]) -> String {
    let mut all_keys: Vec<&KeyDef> = Vec::new();
    for epoch in history {
        for k in &epoch.keys {
            if !all_keys.iter().any(|seen| seen.name == k.name) {
                all_keys.push(k);
            }
        }
    }

    let mut sql = String::new();
    sql.push_str("-- Generated by orc; regenerated on every flush. Do not edit.\n");
    sql.push_str("-- Paths are relative to the data directory, and DuckDB resolves them\n");
    sql.push_str("-- against the process working directory -- not this file's location:\n");
    sql.push_str(&format!(
        "--   cd <data_dir> && duckdb -c \".read series/{series}/view.sql\"\n"
    ));

    if history.is_empty() {
        sql.push_str("-- No epochs recorded for this series yet.\n");
    } else {
        let epochs: Vec<String> = history.iter().map(|e| e.epoch.to_string()).collect();
        sql.push_str(&format!("-- Epochs unioned: {}\n", epochs.join(", ")));
    }

    sql.push_str(&format!(
        "CREATE OR REPLACE VIEW {} AS SELECT\n",
        sql_ident(series)
    ));
    sql.push_str("  ts,\n  id,\n");

    for k in &all_keys {
        let present_everywhere = history
            .iter()
            .all(|e| e.keys.iter().any(|ek| ek.name == k.name));
        let ident = sql_ident(&k.name);
        if present_everywhere {
            sql.push_str(&format!("  {ident},\n"));
        } else {
            // Declared in some epochs, in `extra` in the others.
            //
            // The cast is not optional. `extra`'s values are UTF-8, and DuckDB
            // refuses to coalesce a BIGINT column against a VARCHAR one --
            // "Cannot mix values of type BIGINT and VARCHAR in COALESCE
            // operator - an explicit cast is required" -- so without it this
            // file does not run at all once a non-string key is promoted. Every
            // test covered `string` keys, where the two sides already agree,
            // which is why that went unnoticed.
            //
            // `try_cast`, not `cast`: the `extra` half is whatever some producer
            // wrote there, and a plain cast turns one unparseable value into a
            // Conversion Error that fails the whole query rather than nulling
            // the one row.
            let ty = duckdb_type(k.ty);
            sql.push_str(&format!(
                "  coalesce({ident}, try_cast(extra[{}] AS {ty})) AS {ident},\n",
                sql_str(&k.name)
            ));
        }
    }

    sql.push_str("  extra,\n  data\n");
    sql.push_str(&format!(
        "FROM read_parquet({}, hive_partitioning = 1, union_by_name = 1);\n",
        sql_str(&format!("series/{series}/**/*.parquet"))
    ));
    sql
}

/// Names of every column the generated view exposes, in order.
///
/// Useful for tests and for `orc-cli` to describe a series without parsing SQL.
pub fn view_columns(history: &[EpochSchema]) -> Vec<String> {
    let mut seen = BTreeSet::new();
    let mut cols = vec!["ts".to_string(), "id".to_string()];
    for epoch in history {
        for k in &epoch.keys {
            if seen.insert(k.name.clone()) {
                cols.push(k.name.clone());
            }
        }
    }
    cols.push("extra".to_string());
    cols.push("data".to_string());
    cols
}

#[cfg(test)]
mod tests {
    use super::*;

    fn key(name: &str) -> KeyDef {
        typed_key(name, KeyType::Str)
    }

    fn typed_key(name: &str, ty: KeyType) -> KeyDef {
        KeyDef {
            name: name.to_string(),
            ty,
            nullable: true,
        }
    }

    fn epoch(n: u32, names: &[&str]) -> EpochSchema {
        EpochSchema {
            epoch: n,
            keys: names.iter().map(|n| key(n)).collect(),
        }
    }

    #[test]
    fn stable_key_needs_no_coalesce() {
        let h = [epoch(0, &["symbol"]), epoch(1, &["symbol"])];
        let sql = view_sql("trades", &h);
        assert!(sql.contains("  \"symbol\",\n"), "{sql}");
        assert!(!sql.contains("coalesce"), "{sql}");
    }

    #[test]
    fn promoted_key_is_coalesced_against_extra() {
        // `venue` was undeclared at epoch 0 (so its values are in `extra`) and
        // declared at epoch 1. Reading both halves as one column is the whole
        // reason this file is generated.
        let h = [epoch(0, &["symbol"]), epoch(1, &["symbol", "venue"])];
        let sql = view_sql("trades", &h);
        assert!(sql.contains("  \"symbol\",\n"), "stable key: {sql}");
        assert!(
            sql.contains("coalesce(\"venue\", try_cast(extra['venue'] AS VARCHAR)) AS \"venue\""),
            "promoted key: {sql}"
        );
    }

    /// The `extra` half of a coalesce is always UTF-8, so without a cast back to
    /// the declared type DuckDB resolves the column to VARCHAR — promoting an
    /// `i64` key would silently turn `size > 9` into a string comparison.
    #[test]
    fn a_promoted_key_keeps_the_type_its_config_declares() {
        for (ty, sql_type) in [
            (KeyType::I64, "BIGINT"),
            (KeyType::F64, "DOUBLE"),
            (KeyType::Bool, "BOOLEAN"),
            (KeyType::Str, "VARCHAR"),
        ] {
            let h = [
                EpochSchema {
                    epoch: 0,
                    keys: vec![],
                },
                EpochSchema {
                    epoch: 1,
                    keys: vec![typed_key("size", ty)],
                },
            ];
            let sql = view_sql("trades", &h);
            assert!(
                sql.contains(&format!(
                    "coalesce(\"size\", try_cast(extra['size'] AS {sql_type})) AS \"size\""
                )),
                "{ty:?} should cast to {sql_type}: {sql}"
            );
        }
    }

    #[test]
    fn demoted_key_is_also_coalesced() {
        // Same mechanism in reverse: declared at epoch 0, dropped at epoch 1, so
        // later values arrive in `extra`.
        let h = [epoch(0, &["venue"]), epoch(1, &[])];
        let sql = view_sql("trades", &h);
        assert!(
            sql.contains("coalesce(\"venue\", try_cast(extra['venue'] AS VARCHAR))"),
            "{sql}"
        );
    }

    #[test]
    fn identifiers_and_literals_are_quoted() {
        // A key named after a SQL keyword, and one with a quote in it, must not
        // produce a syntax error or an injection. Two epochs, so the quoted key
        // takes the coalesce path and its name appears as a string literal as
        // well as an identifier -- the two escapings differ.
        let h = [epoch(0, &["select"]), epoch(1, &["select", "it's"])];
        let sql = view_sql("odd\"name", &h);
        assert!(sql.contains("\"select\","), "keyword as ident: {sql}");
        assert!(
            sql.contains("coalesce(\"it's\", try_cast(extra['it''s'] AS VARCHAR)) AS \"it's\""),
            "quote escaped differently in ident vs literal: {sql}"
        );
        assert!(sql.contains("VIEW \"odd\"\"name\""), "escaped ident: {sql}");
    }

    #[test]
    fn empty_history_still_produces_valid_sql() {
        let sql = view_sql("fresh", &[]);
        assert!(sql.contains("CREATE OR REPLACE VIEW \"fresh\""), "{sql}");
        assert!(sql.contains("ts,"), "{sql}");
        assert!(sql.contains("read_parquet("), "{sql}");
    }

    #[test]
    fn columns_are_union_of_all_epochs_in_first_seen_order() {
        let h = [epoch(0, &["a"]), epoch(1, &["a", "b"]), epoch(2, &["b"])];
        assert_eq!(
            view_columns(&h),
            ["ts", "id", "a", "b", "extra", "data"]
                .map(String::from)
                .to_vec()
        );
    }
}
